PIPE-4899 - add build info as input resource for HelmDeploy
jfbetapipeorg/Org_test_Automation pull request #101
Opened 2021-02-23 02:37 UTC by benharosh

PIPE-4899 - add build info as input resource for HelmDeploy
PIPE-4819 - some typo fixes

2021-03-01 10:37 UTC, rageshkrishna requested changes

2021-03-01 10:37 UTC, rageshkrishna commented on tests/yaml/S_HelmDeploy_0024.yml
> +            - export HELM_VERSION=3.4.0
Don't the latest build images already have helm3 on them? Do we still need to download and install this manually in each test?

2021-03-01 10:37 UTC, rageshkrishna commented on tests/yaml/S_HelmDeploy_0026.yml
> +            - helm3 delete simplehelm-generic-$run_id --namespace $K8S_NAMESPACE
Should this be here?

This test case is about verifying that an invalid `chartPath` results in an error. It's expected that nothing will get deployed, but let's assume that doesn't fail the step. Would you still have a failure here because there's nothing to delete, hence hiding the fact that the step didn't fail as it should have?

2021-03-01 10:37 UTC, rageshkrishna commented on tests/yaml/S_PS_HelmDeploy_0005.yml
> +            - $json = @{key="helmgeneric";rclass="local";packageType="generic";description="This repo is a test repo used by test autmation";repoLayoutRef="simple-default"} | ConvertTo-Json -Compress
Typo `autmation` -> `automation`.

2021-03-01 10:37 UTC, rageshkrishna commented on tests/yaml/S_PS_HelmDeploy_0005.yml
> +            - $global:HELM2_VERSION = "2.16.1"
I'm not sure why you're installing both helm2 and helm3. It looks like the step is configured to use helm3, so why bother with 2 at all?

2021-03-01 10:37 UTC, rageshkrishna commented on tests/yaml/S_PS_HelmDeploy_0006.yml
> +            - $json = @{key="simplecharts";rclass="local";packageType="helm";description="This repo is a test repo used by test autmation";repoLayoutRef="simple-default"} | ConvertTo-Json -Compress
Typo `autmation` -> `automation`.

2021-03-01 10:37 UTC, rageshkrishna commented on tests/yaml/S_PS_HelmDeploy_0006.yml
> +            - $global:HELM2_VERSION = "2.16.1"
Is helm2 necessary?

2021-03-01 10:37 UTC, rageshkrishna commented on tests/yaml/S_PS_HelmDeploy_0007.yml
> +            - helm3 delete $simplehelm-generic-$run_id --namespace $k8s_namespace
Same question here about a potential false positive.

2021-03-01 10:37 UTC, rageshkrishna commented on tests/yaml/S_PS_HelmDeploy_0007.yml
> +            - $json = @{key="helmgeneric";rclass="local";packageType="generic";description="This repo is a test repo used by test autmation";repoLayoutRef="simple-default"} | ConvertTo-Json -Compress
Typo `autmation` -> `automation`.

2021-03-01 10:37 UTC, rageshkrishna commented on tests/yaml/S_PS_HelmDeploy_0008.yml
> +            - $json = @{key="simplecharts";rclass="local";packageType="helm";description="This repo is a test repo used by test autmation";repoLayoutRef="simple-default"} | ConvertTo-Json -Compress
Typo `autmation` -> `automation`.

2021-03-01 10:37 UTC, rageshkrishna commented on tests/yaml/S_PS_HelmDeploy_0008.yml
> +            - helm3 delete $simplehelm-from-repo-$run_id --namespace $k8s_namespace
Same question here about a potential false positive.

2021-03-02 04:02 UTC, benharosh commented on tests/yaml/S_PS_HelmDeploy_0006.yml
> +            - $global:HELM2_VERSION = "2.16.1"
I discussed it with JohnS today. We didn't touch the helm commands in this PR, just added support to more input resources, so if helm2 worked before it should continue working. That said, since we didn't have any automation for HelmDeploy we would like to also have automation for helm2 as we do here for helm3. Once I'll finish the coding for supporting ReleaseBundle as input resource I'll fill this gap before the end of this sprint when writing the automation for PIPE-4901. Please don't hold PIPE-4899 and PIPE-4819 because of helm2 - we will tackle that this sprint

2021-03-02 11:07 UTC, rageshkrishna approved these changes

2021-03-12 09:36 UTC, merged