Add helm new function support yaml 10390
jfbetapipeorg/Org_test_Automation pull request #376
Opened 2023-01-09 12:01 UTC by nitind123

Add helm new function support yaml 10390

2023-01-18 05:56 UTC, neha-mishraa requested changes
can you squash all commits

2023-01-31 07:16 UTC, Varsha-Arun commented on helmFile10390-1/.jfrog-pipelines/.jfrog-pipelines/P_SYC_Pipelines_10390_file.yml
> +            env1: 'gitbranch'
why did we add value in quotes

2023-01-31 07:16 UTC, Varsha-Arun commented on tests/uploadTemplate/templates/jfrog/helmTemplate/values.yml
> +    exclude: 'test'
why exclude in quotes and not include

2023-01-31 09:24 UTC, Varsha-Arun approved these changes

2023-01-31 14:48 UTC, nitind123 commented
@neha-mishraa - done ...please merge

2023-02-03 05:36 UTC, neha-mishraa approved these changes

2023-02-03 05:36 UTC, merged